### ISSUE TITLE
Ammo values are not loading from the database properly.

### ISSUE THREAD

**Issue by alexnita3** [alexnita3/GalaxyRP#72]
**Description of the bug (and if possible, steps to reproduce the bug):**
Ammo values are being saved in the database, but are not loaded in-game.

1. Connect to the local server.
2. Log in as a character who has a weapon skill. (or give yourself one `/skillup <name> 21`
3. Run `/kill`.
4. Shoot a few bullets, keeping an eye on the ammo value.
5. Kill yourself.
6. Look into the database with an external software, into the `Weapons` table.
7. The ammo value corresponding to the weapon should've been saved. (and it is)
8. Go back to the game, and respawn.
9. You'll see that the value is reset to the default value, instead of the correct value being grabbed from the database.

**What did you expect to happen instead?**
I would expect the ammo value to be loaded every time someone logs in, and on each respawn.

**Starting point:**
There is a function that is supposed to load the ammo value. (it's possibly not called in the correct place?) Its name is `load_ammo_from_db`.

**Comment by TriForceX** [comment]
I know wheres the problem, but is way bigger than just the ammo. 
The problem is on the respawn function, the data is not loading because theres nothing defined to do there... ive tried to load and it works, but there are other things that doesnt make sense to me, so it has few side-effects. Im trying to figure out why there are some steps that looks unnecesary.

Edit: I also noticed the account connection is removed when you go to spectator, that was planned?

I will tell you if i have news.

**Comment by alexnita3** [comment]
That was not planned, I've put that in because it was crashing the server, it's meant to be a temporary 'fix'. See https://github.com/alexnita3/GalaxyRP/issues/62 for details.

**Comment by alexnita3** [comment]
I meant issue #63 . Have a look at this commit here https://github.com/alexnita3/GalaxyRP/commit/53bd6094fa5ed4bfd1982b1356eb2161f931f755

Sorry, linked the wrong thing in the other comment

**Comment by alexnita3** [comment]
This is fixed now, however, the database system still needs to be refactored to remove some unnecessary calls to methods. Basically, to make it more efficient.
