### ISSUE TITLE
Server log file should be moved into the GalaxyRP folder.

### ISSUE THREAD

**Issue by alexnita3** [alexnita3/GalaxyRP#86]
The file for the server log should be moved into the mod folder so that it's more easily accessible through FTP for hosted servers. (The hosts usually do not give access to the folder where they are stored currently)

**Comment by TriForceX** [comment]
FIxed (Workaround) on commit bc93fce

Note: This can't be done from mod files, the reason is because OpenJK sets the engine cvar "fs_homepath" to be in "My Documents" if the BuildPortableVersion is OFF on CMakeLists when build project files, so every openjkded.exe also will store stuff on "the host documents"... so a workaround is setting the cvar manually to point to the server GameData, fs_ cvars must be loaded before the server starts, so i added it to the Batch launcher to not write the GameData path manually. (The option is toggleable with true or false in the Batch file).
